apiVersion: v2
name: todo
description: A Helm chart for the Todo Application

type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - todo
  - fastapi
  - nextjs
  - kubernetes

maintainers:
  - name: Todo Team
    email: team@todo.app

dependencies:
  - name: postgresql
    version: "15.5.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
