{{- if .Values.aiService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-ai-service
  labels:
    {{- include "todo.aiService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.aiService.service.type }}
  ports:
    - port: {{ .Values.aiService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo.aiService.selectorLabels" . | nindent 4 }}
{{- end }}
